### ISSUE TITLE
clone of existing existing fusion does not work

### ISSUE THREAD

**Issue by rbaertsch** [UCSC-MedBook/MedBook-Fusion#7]
steps to reproduce
1. Make plot
2. post
3. click on post and modify post
4. post
5. open both posts
expected: different plots
got: same plot

**Comment by tedgoldstein** [comment]
Fixed in commit.

**Comment by rbaertsch** [comment]
Is this live on production? I'm still seeing the bug (or a variant).

**Comment by tedgoldstein** [comment]
Lets sit together today and show me.
Thanks,
Ted

**Comment by rbaertsch** [comment]
steps to reproduce:
1. make box plot and post (version 1)
2. click on link in streams to open plot
3. Modify plot (version 2) without posting
4. go back to streams and open version 1 again.
expected: version 1
got: version 2
